// Generated by Wrangler on Sat May 04 2024 20:22:21 GMT+0800 (台北標準時間)
// by running `wrangler types`

interface Env {
	context: KVNamespace;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_BOT_SECRET: string;
}
