#:schema node_modules/wrangler/config-schema.json
name = "223-bot"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "context"
id = "90a422fdfb6f4f88bb5c61bbf9ec0303"

[triggers]
# Schedule cron triggers:
# - At every 3rd minute
crons = [ "0 0 * * *" ]
